### ISSUE TITLE
Make project page more appealing

### ISSUE THREAD

**Issue by locks** [emberwatch/ember-hearth#6]
At the moment, when you click on a project in the sidebar you get transitioned to a blank page.
Either find a way to make this page contain useful and appealing information, or redirect to one of the existing sub-tabs.

**Comment by ynnoj** [comment]
@locks You happy to accept a PR that redirects to an existing route for the time being?

**Comment by locks** [comment]
Yup, I'll keep the issue open but it's a good first step.

**Comment by rwwagner90** [comment]
@locks this sounds like something that would be relatively easy to implement. Could be a good place for me to get my feet wet contributing to ember-hearth. Do you have ideas of what info you would like to display or has this issue already been tackled?

**Comment by locks** [comment]
@rwwagner90 let's talk on Slack
